"""Curriculum inventory. Numbers preserve the learner's original subject list."""
CATALOG = '''
1|Core computer science and systems foundations|Binary; Hexadecimal; Bitwise operations; Signed/unsigned integers; Two's complement; Endianness; Integer overflow/underflow; Floating-point representation; Boolean logic; Arrays; Linked lists; Stacks; Queues; Trees; Hash tables; Algorithms and complexity; Finite-state machines; State machines and event-driven systems; Concurrency; Race conditions; Deadlocks; Synchronization primitives; Processes vs threads; IPC; Virtualization; Containers; Filesystems; Storage fundamentals; Memory hierarchy
2|C mastery|Pointers; Pointer arithmetic; Arrays and pointer decay; Function pointers; Double/triple pointers; Structs; Unions; Bitfields; Enums; Alignment; Padding; Memory layout; Stack vs heap; Dynamic memory allocation; Lifetime and ownership; Undefined behavior; Integer promotion; Type conversions; Volatile; Const; Restrict; Static; Linkage and scope; Preprocessor; Macros; Compilation pipeline; Preprocessing; Compilation; Assembly; Linking; Static libraries; Shared libraries; ELF binaries; ABI; Calling conventions; Syscalls; libc; Cross-compilation; Make/CMake; Compiler optimization; Compiler-generated assembly; Sanitizers; Defensive memory handling
3|Assembly and CPU architecture|x86/x86-64; ARM32; AArch64; MIPS; RISC-V; Registers; Instruction encoding; Addressing modes; Calling conventions; Stack frames; Function prologues/epilogues; Branching; Flags; Interrupts; Exceptions; Privilege levels; Memory protection; MMU; TLB; Caches; Pipelines; Branch prediction; SIMD; Atomic instructions; Memory ordering; CPU boot process
4|Operating systems internals|Kernel architecture; User space vs kernel space; Syscalls; Process creation; Scheduling; Virtual memory; Paging; Page tables; Memory mapping; Signals; File descriptors; Pipes; Sockets; Device drivers; Kernel modules; Interrupt handling; DMA; Character devices; Block devices; /proc; /sys; Linux boot sequence; initramfs; systemd; ELF loading; Dynamic linker; Namespaces; cgroups; Linux capabilities; SELinux/AppArmor concepts; Kernel debugging; Kernel exploitation concepts
5|Computer networking|Ethernet; MAC addresses; ARP; IPv4/IPv6; ICMP; TCP; UDP; DNS; DHCP; NAT; Routing; Switching; VLANs; VPNs; TLS; HTTP; MQTT; CoAP; WebSockets; Packet fragmentation; Stateful protocols; Packet capture; Protocol dissection; Network segmentation; Firewalls; IDS/IPS; Network namespaces; Software-defined networking concepts
6|Reverse engineering|Static analysis; Dynamic analysis; Disassembly; Decompilation; Control-flow analysis; Data-flow analysis; Cross-references; Function identification; Symbol recovery; Type reconstruction; Stack-variable reconstruction; Calling-convention identification; Compiler idioms; Optimization artifacts; Switch/jump tables; Virtual functions; C++ name mangling; RTTI; Exception handling; ELF; PE; Mach-O; Relocations; GOT; PLT; Dynamic linking; Symbol tables; Debug information; Stripped binaries; Packers; Obfuscation; Anti-debugging; Anti-analysis; Self-modifying code; Binary diffing; Patch analysis; Program slicing; Taint analysis; Symbolic execution; Concolic execution
7|Debugging|Breakpoints; Hardware breakpoints; Watchpoints; Single stepping; Register inspection; Stack inspection; Memory inspection; Core dumps; Remote debugging; GDB internals; ptrace; Debug symbols; JTAG debugging; SWD debugging; Kernel debugging; Emulator-assisted debugging
8|Binary exploitation and vulnerability research|Stack buffer overflows; Heap overflows; Integer vulnerabilities; Format-string vulnerabilities; Use-after-free; Double-free; Null-pointer dereferences; Type confusion; Out-of-bounds access; Race conditions; Logic vulnerabilities; Memory corruption; Shellcode concepts; ROP; JOP; Stack pivoting; Return-to-libc; ASLR; DEP/NX; Stack canaries; PIE; RELRO; CFI; PAC; Shadow stacks; Heap allocators; glibc malloc internals; Exploit reliability; Crash triage; Root-cause analysis; Fuzzing; Coverage-guided fuzzing; Mutation fuzzing; Grammar-based fuzzing; Harness design; Sanitizers
9|Electronics fundamentals|Voltage; Current; Resistance; Power; Ohm's law; Kirchhoff's laws; AC vs DC; Digital vs analog signals; Logic levels; Pull-up/pull-down resistors; GPIO; PWM; ADC; DAC; Transistors; MOSFETs; Diodes; Capacitors; Inductors; Oscillators; Crystals; Voltage regulators; Level shifting; Power supplies; Signal integrity; Grounding; ESD; Datasheet interpretation; Schematics
10|Digital electronics|Logic gates; Flip-flops; Registers; Counters; Multiplexers; Clock domains; Buses; State machines; Timing; Setup/hold time; Combinational logic; Sequential logic; Memory devices; SRAM; DRAM; NOR flash; NAND flash; EEPROM; FPGA fundamentals; CPLD fundamentals
11|Hardware hacking|PCB identification; PCB tracing; Test points; Multimeter usage concepts; Oscilloscope concepts; Logic analyzers; Bus sniffing; UART; SPI; I²C; JTAG; SWD; CAN; USB; PCIe fundamentals; SD/eMMC; NAND; NOR flash; Flash dumping; Boot pins; Debug interfaces; Hardware breakpoints; Board bring-up; Chip identification; Datasheet research; Soldering/rework concepts; BGA concepts; Fault injection concepts; Voltage glitching concepts; Clock glitching concepts; Side-channel concepts; Power analysis; EM analysis; Secure elements; Hardware roots of trust
12|Embedded systems|Microcontrollers; Microprocessors; SoCs; ARM Cortex-M; ARM Cortex-A; RISC-V MCUs; Memory-mapped I/O; Interrupts; Interrupt vector tables; Timers; Watchdogs; GPIO; ADC/DAC; DMA; Peripheral registers; Bootloaders; Linker scripts; Startup code; Bare-metal programming; Cross-compilation; Embedded C; RTOS concepts; Tasks; Scheduling; Semaphores; Mutexes; Queues; Interrupt latency; Real-time constraints; Device trees; Board support packages; HALs
13|Firmware development|MCU startup sequence; Reset vectors; Linker scripts; Memory maps; Flash layouts; Bootloaders; Secure boot; Firmware update mechanisms; OTA updates; Peripheral drivers; Interrupt-driven programming; Embedded networking; RTOS development; Hardware abstraction layers; Power management; Watchdogs; Fault handling; Firmware signing; Rollback protection; Cryptographic verification; Firmware debugging; Firmware testing; Production provisioning
14|Firmware reverse engineering|Firmware extraction; Flash dumps; Filesystem extraction; SquashFS; UBIFS; JFFS2; CramFS; YAFFS; U-Boot; BusyBox; Embedded Linux; Firmware entropy analysis; Compression; Encryption recognition; Firmware signatures; Binary blobs; Device trees; Kernel images; Root filesystem analysis; Init scripts; Hardcoded secrets; Configuration analysis; Update-package analysis; Firmware emulation; Partial emulation; Peripheral emulation
15|IoT architecture|Sensors; Actuators; Gateways; Edge computing; Cloud backends; Device provisioning; Device identity; Device lifecycle; Telemetry; Command-and-control models; MQTT; CoAP; AMQP; BLE; Zigbee; Thread; Matter; Z-Wave; Wi-Fi; LoRa/LoRaWAN; Cellular IoT; NB-IoT; LTE-M; GNSS; IoT authentication; Device certificates; PKI; Secure onboarding; OTA updates; Cloud-device trust relationships
16|IoT security|Hardware trust boundaries; Firmware vulnerabilities; Insecure boot; Insecure update systems; Default credentials; Weak authentication; API security; Mobile-app interaction; Cloud API interaction; Protocol vulnerabilities; Local network attack surfaces; Physical attack surfaces; Device identity attacks; Key extraction; Supply-chain security; Secure provisioning; Device decommissioning; IoT botnets; Fleet management security
17|Wireless and RF fundamentals|Frequency; Wavelength; Modulation; ASK; FSK; PSK; QAM; OFDM; Spectrum; Channels; Bandwidth; Noise; SNR; Antennas; RF propagation; SDR concepts; Protocol demodulation; Packet decoding; BLE security; Wi-Fi security; Zigbee security; LoRa security; RFID; NFC
18|Cryptography|Entropy; Random-number generation; Hash functions; MAC/HMAC; Symmetric encryption; AES; Stream ciphers; Block cipher modes; Public-key cryptography; RSA; ECC; Diffie-Hellman; Digital signatures; Certificates; PKI; Key derivation; Key storage; Key rotation; Secure boot chains; Hardware-backed keys; TPM; HSM; Secure elements; Cryptographic implementation failures; Side-channel fundamentals
19|Malware analysis|Static malware analysis; Dynamic malware analysis; Behavioral analysis; Sandboxing; Process injection; DLL/shared-library loading; Persistence mechanisms; Privilege escalation concepts; Command-and-control architectures; Network indicators; Filesystem indicators; Registry concepts for Windows malware; Linux persistence; Rootkits; Bootkits; Kernel malware; Userland malware; Packed binaries; Obfuscation; Encryption; API hashing; Anti-debugging; Anti-VM techniques; Process hollowing concepts; Hooking; Syscall usage; Configuration extraction; Malware family clustering; YARA concepts; IOC extraction; Behavioral signatures
20|Windows internals for malware analysis|PE format; Windows processes; Threads; Handles; Virtual memory; Windows API; Native API; DLL loading; Registry; Services; Tokens; Access control; Windows kernel concepts; Drivers; ETW; AMSI; COM; WMI; PowerShell architecture
21|Linux internals for malware and embedded research|ELF; /proc; /sys; Syscalls; ptrace; Kernel modules; eBPF concepts; Dynamic linker; LD_PRELOAD; Capabilities; Namespaces; cgroups; init systems; cron; systemd services; Kernel rootkits; Embedded Linux architecture
22|ICS/OT fundamentals|Industrial control systems; Operational technology; PLCs; RTUs; HMIs; SCADA; DCS; SIS; Historians; Engineering workstations; Industrial gateways; Remote I/O; VFDs; Motor controllers; Sensors; Actuators; Relays; Process controllers; Safety controllers
23|Industrial process fundamentals|Feedback control; Open-loop vs closed-loop control; PID control; Setpoints; Process variables; Control variables; Interlocks; Alarms; Trip conditions; Safety systems; Redundancy; Fail-safe design; Availability requirements; Determinism; Real-time control; Physical-process consequences; Electrical systems basics; Motors; Pumps; Valves; Pressure; Temperature; Flow; Level control
24|PLC programming|IEC 61131-3; Ladder Logic; Structured Text; Function Block Diagram; Sequential Function Charts; Instruction List historically; PLC scan cycle; Inputs/outputs; Tags; Registers; Timers; Counters; Function blocks; Data blocks; Retentive memory; PLC state; Online monitoring; PLC firmware
25|Industrial protocols|Modbus RTU; Modbus TCP; Siemens S7; PROFINET; PROFIBUS; EtherNet/IP; CIP; OPC; OPC UA; DNP3; IEC 60870-5-104; IEC 61850; BACnet; HART; CAN; CANopen; EtherCAT; Foundation Fieldbus; MQTT in industrial environments; Serial communications; RS-232; RS-485
26|ICS networking|Purdue Model; Zones and conduits; OT network segmentation; Industrial DMZs; Air gaps; Unidirectional gateways; Data diodes; Industrial firewalls; Jump hosts; Remote-access architectures; Redundant networks; Deterministic Ethernet; Asset discovery; Passive monitoring; Protocol-aware monitoring
27|ICS security|OT threat modeling; IT vs OT priorities; Safety vs security; Availability requirements; Legacy systems; Insecure-by-design protocols; Engineering workstation compromise; PLC logic modification; Firmware attacks; HMI attacks; Historian attacks; Safety-system attacks; Remote-access risk; Supply-chain risk; Segmentation; Application allowlisting; Secure remote access; Asset inventory; Configuration management; Patch-management constraints; Incident response in operational environments; Recovery engineering; Cyber-physical impact analysis
28|ICS security frameworks and models|IEC 62443 concepts; NIST Cybersecurity Framework; NIST SP 800-82 concepts; MITRE ATT&CK for ICS; Zones and conduits; Security levels; Defense in depth; Functional safety concepts; Safety integrity levels; Risk assessment; Threat modeling; Consequence-driven security
29|ICS malware and cyber-physical attacks|PLC manipulation; Process manipulation; Engineering software abuse; Protocol abuse; Man-in-the-middle attacks; Replay attacks; Command manipulation; Sensor spoofing; Actuator manipulation; Safety-system interference; Living-off-the-land in OT; ICS malware architecture; Cyber-physical attack chains
30|Embedded and ICS protocol reverse engineering|Packet captures; Binary protocol formats; Message framing; Checksums; CRCs; Sequence numbers; Session state; State-machine inference; Field identification; Differential analysis; Protocol fuzzing; Proprietary protocol analysis; Serial protocol analysis; RF protocol analysis
31|Boot and trusted-computing architecture|ROM bootloaders; First-stage bootloaders; Second-stage bootloaders; U-Boot; BIOS; UEFI; Secure Boot; Measured boot; Chain of trust; TPM; Trusted execution environments; ARM TrustZone; Firmware signing; Anti-rollback; Device attestation; Root of trust
32|Hardware security|Threat modeling for silicon; Debug-port security; Secure boot; Key storage; Fuses; OTP memory; Secure elements; TPMs; TEEs; Side-channel analysis; Fault injection; Glitch attacks; Cold-boot concepts; Bus interception; Flash extraction; Chip-off concepts; Supply-chain threats
33|Virtualization and emulation|QEMU; CPU emulation; System emulation; User-mode emulation; Hardware virtualization; Hypervisors; Virtual networking; Snapshots; Instrumentation; Firmware emulation; Peripheral emulation; Digital twins; ICS simulation
34|Program analysis|Control-flow graphs; Data-flow graphs; SSA; Call graphs; Taint analysis; Symbolic execution; Constraint solving; Abstract interpretation; Program slicing; Static analysis; Dynamic instrumentation; Binary instrumentation; Coverage analysis
35|Fuzzing and automated vulnerability discovery|Mutation-based fuzzing; Generation-based fuzzing; Coverage-guided fuzzing; Grammar fuzzing; Protocol fuzzing; Firmware fuzzing; Hardware-in-the-loop fuzzing; Snapshot fuzzing; Harness creation; Corpus management; Crash deduplication; Crash minimization; Root-cause analysis; Coverage measurement
36|Python for security research|Binary parsing; struct; Sockets; Serial communications; Packet manipulation; Automation; Debugger scripting; Disassembler scripting; Firmware parsing; Protocol implementation; Fuzzing harnesses; Data extraction; ELF/PE parsing concepts
37|Software engineering|Git; Build systems; Unit testing; Integration testing; Continuous integration; Debugging; Logging; Profiling; API design; Code review; Documentation; Reproducible builds; Dependency management; Static analysis; Secure coding
38|Security engineering|Threat modeling; Attack surfaces; Trust boundaries; Least privilege; Defense in depth; Authentication; Authorization; Access control; Secrets management; Secure update architecture; Secure boot; Key management; Secure provisioning; Supply-chain security; Software bill of materials; Vulnerability management; Security architecture
39|Vulnerability research methodology|Attack-surface mapping; Entry-point identification; Trust-boundary analysis; Data-flow analysis; Code auditing; Binary auditing; Firmware auditing; Protocol auditing; Hardware auditing; Fuzzing; Differential testing; Patch diffing; Crash analysis; Root-cause analysis; Exploitability assessment; Reproduction; Responsible disclosure; CVE/CWE concepts
40|Security research mathematics|Boolean algebra; Modular arithmetic; Probability; Statistics; Information theory; Entropy; Discrete mathematics; Graph theory; Number theory fundamentals; Finite fields for cryptography; Basic signal-processing mathematics
41|Research skills|Datasheet reading; Technical manual analysis; Patent research; Standards reading; RFC reading; Source-code archaeology; Binary-to-source correlation; Scientific experimentation; Hypothesis formation; Controlled experiments; Reproducibility; Technical note-taking; Reverse-engineering documentation; Writing vulnerability reports; Writing technical research papers
42|Physical and operational safety|Electrical safety; ESD precautions; Isolation; High-voltage awareness; Industrial safety; Fail-safe operation; Safety interlocks; Hardware lab safety; Safe malware isolation; Network isolation; Controlled ICS testing; Responsible disclosure; Authorization boundaries
'''
# Foundations and safety precede C; supporting branches feed back into the main chain.
ORDER = [42, 1, 40, 41, 37, 2, 3, 4, 21, 5, 36, 7, 6, 8, 9, 10, 12, 11, 18, 31, 13, 14, 32, 15, 17, 16, 25, 23, 24, 22, 26, 38, 28, 27, 20, 19, 29, 33, 30, 34, 35, 39]
CATALOG = {int(n): {'id': int(n), 'title': title, 'topics': topics.split('; ')}
           for n, title, topics in (line.split('|') for line in CATALOG.strip().splitlines())}
