"""Primary-source reading paths. External reading is opened only on user request."""
SOURCES = {
'c': ('GNU C language introduction and reference', 'https://www.gnu.org/software/c-intro-and-ref/manual/html_node/'),
'arch': ('RISC-V instruction set specifications', 'https://docs.riscv.org/reference/isa/'),
'linux': ('Linux kernel documentation', 'https://docs.kernel.org/'),
'network': ('RFC 9293: TCP specification', 'https://www.rfc-editor.org/rfc/rfc9293.html'),
're': ('Ghidra documentation and training', 'https://ghidra.re/ghidra_docs/GhidraClass/Beginner/Introduction_to_Ghidra_Student_Guide.html'),
'debug': ('GNU GDB manual', 'https://sourceware.org/gdb/current/onlinedocs/gdb.html/'),
'san': ('Clang AddressSanitizer documentation', 'https://clang.llvm.org/docs/AddressSanitizer.html'),
'elec': ('MIT OpenCourseWare: Circuits and Electronics', 'https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/'),
'digital': ('MIT OpenCourseWare: Computation Structures', 'https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/'),
'embedded': ('Zephyr Project documentation', 'https://docs.zephyrproject.org/latest/'),
'boot': ('U-Boot documentation', 'https://docs.u-boot.org/en/latest/'),
'crypto': ('NIST cryptographic standards and guidelines', 'https://csrc.nist.gov/projects/cryptographic-standards-and-guidelines'),
'iot': ('NIST IoT cybersecurity program', 'https://www.nist.gov/itl/applied-cybersecurity/nist-cybersecurity-iot-program'),
'mqtt': ('OASIS MQTT 5.0 specification', 'https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html'),
'rf': ('GNU Radio tutorials', 'https://wiki.gnuradio.org/index.php/Tutorials'),
'attack': ('MITRE ATT&CK for ICS', 'https://attack.mitre.org/matrices/ics/'),
'windows': ('Microsoft: Windows internals', 'https://learn.microsoft.com/en-us/sysinternals/resources/windows-internals'),
'ot': ('NIST SP 800-82 Rev. 3: Guide to OT Security', 'https://csrc.nist.gov/pubs/sp/800/82/r3/final'),
'modbus': ('Modbus Organization: protocol specifications', 'https://www.modbus.org/modbus-specifications'),
'plc': ('CODESYS: PLC programming documentation', 'https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_struct_reference_programming.html'),
'qemu': ('QEMU documentation', 'https://www.qemu.org/docs/master/'),
'analysis': ('LLVM language reference', 'https://llvm.org/docs/LangRef.html'),
'fuzz': ('LLVM libFuzzer documentation', 'https://llvm.org/docs/LibFuzzer.html'),
'python': ('Python struct: interpreting binary data', 'https://docs.python.org/3/library/struct.html'),
'git': ('Git reference documentation', 'https://git-scm.com/docs'),
'cwe': ('MITRE CWE: weakness catalog', 'https://cwe.mitre.org/'),
'math': ('MIT OpenCourseWare: Mathematics for Computer Science', 'https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/'),
'rfc': ('RFC Editor: official RFC series', 'https://www.rfc-editor.org/'),
'safety': ('OSHA electrical safety resources', 'https://www.osha.gov/electrical'),
}
READING = {
1: ('c', 'math'), 2: ('c', 'san'), 3: ('arch', 'debug'), 4: ('linux', 'debug'),
5: ('network', 'rfc'), 6: ('re', 'debug'), 7: ('debug', 'linux'), 8: ('san', 'cwe'),
9: ('elec', 'safety'), 10: ('digital', 'elec'), 11: ('embedded', 'elec'),
12: ('embedded', 'arch'), 13: ('boot', 'embedded'), 14: ('boot', 're'),
15: ('mqtt', 'iot'), 16: ('iot', 'cwe'), 17: ('rf', 'rfc'), 18: ('crypto', 'boot'),
19: ('attack', 're'), 20: ('windows', 'debug'), 21: ('linux', 'debug'),
22: ('ot', 'attack'), 23: ('ot', 'plc'), 24: ('plc', 'ot'), 25: ('modbus', 'mqtt'),
26: ('ot', 'network'), 27: ('ot', 'attack'), 28: ('ot', 'attack'), 29: ('attack', 'ot'),
30: ('modbus', 'python'), 31: ('boot', 'crypto'), 32: ('crypto', 'embedded'),
33: ('qemu', 'embedded'), 34: ('analysis', 're'), 35: ('fuzz', 'san'),
36: ('python', 'debug'), 37: ('git', 'san'), 38: ('iot', 'cwe'), 39: ('cwe', 'fuzz'),
40: ('math', 'crypto'), 41: ('rfc', 'git'), 42: ('safety', 'ot'),
}
