"""Authored guided lessons. Worked examples deliberately differ from assessment cases."""
TEACHING = {}
VERSION = '2026.09.guided.2'

def lesson(number, purpose, model, mechanism, example, steps, failure, repair, question, options):
    TEACHING[number] = dict(purpose=purpose, mental_model=model, mechanism=mechanism,
        example=example, steps=steps.split('|'), failure=failure, repair=repair,
        prediction=dict(question=question, options=options.split('|')),
        version=VERSION)

lesson(42,
'Every later experiment depends on knowing what it may affect. Learning isolation first prevents a software exercise from quietly becoming an experiment on a real device.',
'Treat an experiment as a boundary containing assets, communication paths, energy sources, permitted actions, and explicit stop conditions.',
'Authorization answers whether an action is permitted. Isolation limits where its effects can travel. Neither implies the other: an authorized asset can still have unsafe connections, and an isolated asset can still be outside your permission. A snapshot restores selected state; it cannot undo an external physical action.',
'A simulated temperature controller has recorded sensor input and no outputs. Someone proposes adding a USB-connected motor for realism.',
'List the original boundary: simulator, recorded data, and local storage.|Trace the new path: controller command → USB device → motor movement.|The change introduces physical effects that the original software-only permission and recovery plan did not cover.',
'An experiment fails its boundary assumptions when a new route, shared folder, credential, peripheral, or energy source reaches beyond the approved setup. Merely naming a network “isolated” does not prove the boundary.',
'Keep this exercise simulated. Review the connection and authorization before changing the boundary. Record what must remain disconnected and what observation requires stopping. Electrical isolation and competent physical safety procedures are separate from network configuration.',
'What should happen before adding the motor?',
'Stop and reassess permission and physical safeguards|Continue because the simulator was already approved|Take a snapshot and assume physical effects can be undone')

lesson(1,
'Programs ultimately transform finite representations and shared state. You need this foundation to explain why a calculation, memory access, or concurrent operation differs from mathematical intuition.',
'Track representation, interpretation, legal states, and transitions separately. Always name the width, signedness, unit, and synchronization assumption.',
'Four bits have sixteen distinct patterns. Unsigned interpretation assigns them 0–15; two’s complement assigns the top bit a negative weight. Reducing an unsigned result to a fixed width retains the low bits, equivalent to a remainder. This does not establish C signed-overflow behavior. Endianness matters only when interpreting multiple bytes. At larger scales, data structures choose how state is stored and algorithms choose the work needed to transform it.',
'A four-bit unsigned counter starts at 14 and advances by 3. It has wrapping storage, not saturation.',
'The mathematical sum is 17.|Write 17 as binary 10001; a four-bit destination retains 0001.|The stored value is 1, also 17 modulo 16. A wider five-bit destination would retain 17.',
'Assuming unlimited integers hides wraparound. Assuming read–modify–write is one action hides races: two threads can both read 7 and each write 8. A lock can protect that transition, but inconsistent lock order can create a cycle of waiting.',
'Write down the representation contract, check ranges before narrowing, and identify shared-state transitions. Choose structures by access patterns and complexity, then measure locality and contention rather than treating big-O as a stopwatch.',
'What would the example store in a five-bit unsigned destination?',
'17|1|15')

lesson(2,
'C exposes object representation and lifetime directly, so it connects source code to the memory behavior you will later inspect in assembly and crash reports.',
'A pointer is a typed route to a live object within bounds, not permission to access every nearby address. Track base object, element size, index, lifetime, and ownership.',
'Array indexing a[i] is defined through pointer arithmetic and dereferencing. Arithmetic scales by the pointed-to type. The address calculation alone does not prove the object exists or is live. Array-to-pointer conversion loses array extent; a function receiving a pointer normally needs a separate length. Types, alignment, compilation, and the ABI constrain how the source becomes machine operations.',
'Assume short occupies two bytes. short values[4] = {3, 6, 9, 12} begins at 0x2000. Consider values + 1.',
'The base identifies element zero at 0x2000.|One element advances two bytes, reaching 0x2002.|Dereferencing yields 6. values + 4 may denote one-past, but dereferencing it does not access a fifth element.',
'An address may be mapped yet outside the object. Freed storage may still contain old bytes yet no longer have the required lifetime. Optimizers assume defined behavior; one apparently successful run cannot make an invalid access valid. volatile does not establish thread ownership or atomicity.',
'Carry lengths with pointers, define who releases allocations, avoid stale aliases, and check multiplication before allocating count × element-size bytes. Use compiler warnings and sanitizers as evidence. For copying, validate both source availability and destination capacity.',
'How far does values + 2 advance under the stated size assumption?',
'Four bytes|Two bytes|Eight bytes')

lesson(3,
'Assembly lets you test what a compiled program actually does. Architecture supplies the meaning of instructions; a microarchitecture explains many performance effects without changing that contract.',
'Model each instruction as a transition of registers, flags, memory, and the instruction pointer, interpreted under a specific ISA and ABI.',
'A register can hold a value that happens to look like an address without causing a memory access. Address-expression arithmetic and dereferencing are distinct operations. Calling conventions determine which registers initially carry arguments and which must survive calls. Caches and pipelines affect execution cost; they do not let you invent different architectural results.',
'In a toy System V AMD64 function, rdi = 2 and rsi = 6. The instruction is lea eax, [rdi + rsi*2].',
'Read the register operands: 2 and 6.|Calculate 2 + 6 × 2 = 14.|LEA places the arithmetic result in EAX without loading memory at address 14. Under this ABI the integer return value is taken from EAX.',
'Transferring argument-register assumptions to another ABI produces wrong input values. Treating LEA like a load invents a memory dependency. Optimized functions may omit familiar stack frames, so a missing prologue is not proof of malformed code.',
'Identify ISA, operand width, signedness, and ABI first. Trace small instruction sequences and compare a predicted register table with a debugger. Separate address translation, access permissions, and cache behavior when explaining a fault or slowdown.',
'Does this LEA need readable memory at address 14?',
'No, it computes an expression without a memory load|Yes, it loads fourteen bytes|Only when the caller is written in C')

lesson(4,
'Kernel abstractions explain how programs share resources while appearing to have private files, memory, and execution. They are essential for interpreting Linux traces.',
'Distinguish a process-local name or handle from the kernel object it references and the state shared through that object.',
'A file descriptor is a small table index. The open file description holds state including the current offset. Duplicating a descriptor creates another reference to that description; opening the pathname again normally creates a new description. The same distinction recurs with virtual addresses, mappings, sockets, and namespace views: names are not the underlying resources.',
'A file contains WXYZ. Descriptor a is opened, b = dup(a), and a reads one byte before b reads one byte.',
'Both descriptors refer to one open file description whose offset begins at zero.|Reading through a returns W and moves the shared offset to one.|Reading through b returns X, then advances that same offset again.',
'Assuming different descriptor numbers imply independent offsets makes concurrent readers consume unexpected positions. Assuming a page fault always means invalid memory confuses demand allocation with a protection failure. Namespace separation alone does not constrain every privilege or resource.',
'Draw references and shared objects explicitly. Use separate opens or position-based reads when independent file positions are required. Check mapping flags, permissions, and error results instead of inferring semantics from identifier values.',
'If b comes from a separate open before either read, what does b read first?',
'W|X|Nothing, because one file may only be opened once')

lesson(5,
'Networking connects process behavior to packets and application protocols. Without a layered model, it is easy to confuse reliable delivery with message framing or encryption with permission.',
'Trace bytes across link, network, transport, and application boundaries. Ask which layer provides addressing, ordering, framing, identity, and authorization.',
'TCP preserves an ordered stream of bytes. A send call contributes bytes; a recv call consumes currently available bytes up to its requested limit. Those call boundaries need not correspond. Application protocols therefore encode their own record boundaries. UDP supplies datagrams but not TCP’s delivery behavior. Routing decides a path; a firewall decides which flows policy permits.',
'A sender writes CAT and then DOG. One receive returns CA and the next returns TDOG.',
'The stream is C A T D O G, six ordered bytes.|The first read consumes two bytes; four remain.|The second read can combine the remainder of the first write and all of the second. No bytes were reordered and no record guarantee was violated.',
'A parser that treats each receive as a full message may process incomplete records or combine two commands. Encryption does not repair framing. A successful TLS handshake also does not decide whether this identity may use a particular application resource.',
'Use a length prefix or a delimiter with a defined escaping rule, buffer partial records, and handle multiple records per read. Bound lengths and timeouts. Inspect traces at the right layer and distinguish encrypted payload visibility from connection metadata.',
'If recv asks for 100 bytes, must it return both writes as separate records?',
'No; application framing is still required|Yes; a large buffer creates message boundaries|Yes; TCP preserves send-call boundaries')

lesson(6,
'Reverse engineering turns observations of an unfamiliar binary into testable hypotheses. It lets you study behavior when source code is missing or misleading.',
'Recover a chain from inputs through transformations and conditions to outputs; treat names, types, and decompiler output as hypotheses until checked.',
'Static analysis identifies possible paths; dynamic analysis observes one execution. A comparison reveals a constraint on transformed input. Reversing a reversible operation can solve that constraint, but only after confirming widths and intermediate transformations. Cross-references and calling conventions help find where values come from and where results are used.',
'Recovered toy logic accepts x when (x XOR 0x20) == 0x61. x is an eight-bit value with no earlier transformation.',
'XOR each side with 0x20.|Because a XOR b XOR b = a, the required x is 0x61 XOR 0x20 = 0x41.|Substitute 0x41 into the original expression to verify that the comparison is true.',
'A decompiler can infer the wrong signedness or merge variables. A string named password does not prove the branch authenticates a user. An observed successful execution proves a path is reachable, not that other paths are impossible.',
'Validate important expressions against instructions, recover input transformations, and test both a matching and nonmatching input in a synthetic trace. Record uncertain types and environmental assumptions. Use symbols and debug data as supporting evidence rather than guaranteed original intent.',
'What gives stronger evidence than renaming x to password?',
'Checking the predicted comparison in the instruction trace|Choosing a convincing variable name|Finding the executable in a folder called secure')

lesson(7,
'Debugging connects an observed failure to the first state change that made it possible. The last crashing instruction is often only the messenger.',
'Track an invariant through time and choose an observation tool that stops where that invariant changes.',
'A breakpoint observes control reaching an instruction. A data watchpoint observes access or change at a selected memory location. A core dump preserves a later state. If an index becomes invalid before it is used, observing the write can reveal the responsible caller and values sooner than stopping at the fault.',
'A synthetic index is 2, later becomes 3, then an unexpected writer stores -4. Much later a buffer access fails.',
'State the invariant: valid index values must be within the buffer’s range.|Locate the storage whose value changes and watch writes to it.|At the unexpected write, inspect the instruction, call stack, and input that produced -4.',
'An optimized variable may have no stable memory address. A watchpoint has finite hardware resources and may watch the wrong lifetime after storage reuse. Stopping execution also changes timing, which can hide races or disrupt real-time systems.',
'Confirm address and lifetime, inspect disassembly when source locations are ambiguous, and distinguish first invalid state from later symptoms. Use recorded or simulated targets for timing-sensitive exercises and reproduce without the debugger where possible.',
'Which event is closest to the root cause in this example?',
'The write that first makes the index invalid|The later attempt to read the buffer|Opening the core dump file')

lesson(8,
'Vulnerability research begins by explaining violated invariants. Understanding the defect before discussing exploitation keeps root cause, impact, and mitigation distinct.',
'Compare every memory operation against the destination’s bounds, the source’s bounds, and both objects’ lifetimes. Then separately evaluate possible consequences.',
'A buffer overflow occurs when a write exceeds an object’s extent. It may affect adjacent data even if no executable code is introduced. The write length, object size, and reachable path establish the defect; the surrounding layout and mitigations influence consequences. Stack and heap placement change context, not the basic bounds requirement.',
'A synthetic trace copies nine bytes into a six-byte destination. The source really contains nine bytes.',
'The valid destination offsets are zero through five.|The copy requests offsets zero through eight.|Offsets six, seven, and eight are outside the object: three bytes exceed the destination, regardless of whether a crash is observed.',
'Checking that a length is nonnegative does not establish an upper bound. A canary can detect some corruption after it happens; NX restricts execution permissions but does not make the write valid. Integer wrap during a size calculation can invalidate a later comparison.',
'Validate the intended copy length against actual capacity before writing; reject oversize input or define an explicit truncation policy. Check source availability and arithmetic too. For strings, account for terminators. Add boundary tests and sanitizer runs, then explain what the fix establishes and what it does not.',
'Would enabling NX make the nine-byte copy fit in the six-byte object?',
'No; execution permission does not change object bounds|Yes; NX truncates the write|Yes; only executable buffers can overflow')

lesson(9,
'Physical signals obey electrical constraints even when software calls them zero and one. Electronics gives you the vocabulary to reason from a schematic to a plausible measurement.',
'Track potential differences, current paths, component behavior, units, and power rather than treating a wire as an abstract Boolean connection.',
'For an ideal ohmic resistor, I = V/R. Current through a component depends on voltage across it, not simply on the supply label. Power P = VI describes energy transfer rate. Kirchhoff’s laws constrain currents at nodes and voltages around loops. Real components add tolerances, heating, and operating limits.',
'On paper only, an ideal 5 V source is connected across a 1000 ohm resistor.',
'Identify the voltage across the resistor: 5 V.|Compute current: 5/1000 = 0.005 A = 5 mA.|Compute dissipation: 5 × 0.005 = 0.025 W. The unit conversion is part of the result, not cosmetic formatting.',
'Using the wrong unit creates thousandfold errors. A digital input can be damaged by an incompatible voltage even when its nominal signal is “high.” A missing reference ground can make two measured voltages incomparable.',
'Check voltage limits, current ratings, thresholds, and reference points in the relevant documentation. In this module use paper calculations and simulated signals. Physical work requires appropriate training and equipment; the calculation does not authorize connecting real energized equipment.',
'With the same ideal resistor and half the voltage, what happens to current?',
'It halves|It doubles|It stays fixed because resistance is unchanged')

lesson(10,
'Digital electronics explains how continuous voltages become stored state and why timing matters even when a truth table looks correct.',
'Distinguish combinational outputs determined by present inputs from sequential outputs determined by sampled inputs and previous state.',
'A flip-flop captures data at a specified clock edge, then retains the captured value between edges. Its setup and hold contract requires stability around the sampling event. A register groups flip-flops; a counter combines a register with next-state logic. A bus protocol adds rules about who drives signals and when receivers may sample them.',
'A positive-edge D flip-flop has Q = 1. D becomes 0 well before the next rising edge and stays stable through that edge.',
'Before the rising edge, Q retains its old value 1.|At the edge, the stable D value 0 is captured.|After propagation settles, Q is 0 and remains so until another active edge changes it.',
'If data changes in the sampling window, metastability can make the observed state or settling time unreliable. A correct static truth table does not establish timing closure. Separate clock domains cannot assume a shared sampling instant.',
'Use an explicit timing diagram and identify clock domains. Synchronizers reduce metastability propagation risk for suitable signals; multi-bit transfers need an appropriate handshake or FIFO scheme. Check reset and retention behavior in addition to normal transitions.',
'Before the active edge, does Q immediately follow D down to zero?',
'No; it retains the previous captured state|Yes; all digital storage is combinational|Only if the input is named data')

lesson(11,
'Hardware investigation requires turning an observed waveform into a defensible interpretation before connecting tools or drawing security conclusions.',
'Separate physical identification, electrical compatibility, sampling, framing, and byte interpretation; validate each layer instead of guessing from connector shape.',
'An asynchronous UART frame supplies a start transition, a configured number of data bits, optional parity, and stop framing. In an LSB-first data field, the first bit contributes 2^0, the next 2^1, and so on. A logic analyzer reports thresholded samples; incorrect voltage thresholds or sample timing can make correct-looking decoding meaningless.',
'An inert 8N1 capture has a valid start and stop. Its eight data bits, earliest first, are 0 1 0 0 0 0 1 0.',
'Assign weights 1, 2, 4, 8, 16, 32, 64, 128 in observation order.|Only weights 2 and 64 are set, totaling 66, or 0x42.|Under ASCII, 0x42 is capital B. Start and stop bits are framing, not part of the character.',
'Reversing bit order changes the value. Treating any idle-high line as UART skips protocol identification. A pin that looks like a debug connection can belong to a different voltage domain or peripheral.',
'Use datasheets, board evidence, and several consistent frames to check the hypothesis. Preserve the original capture and decoder settings. This exercise uses recorded data only; do not infer a safe live connection from a successful byte calculation.',
'Are the start and stop bits included in the eight-bit ASCII value?',
'No; they delimit the data field|Yes; they are the two most significant bits|Only when the character is uppercase')

lesson(12,
'Embedded software controls peripherals whose registers do not necessarily behave like RAM. Understanding register contracts prevents subtle event loss and timing errors.',
'A peripheral access is an operation on a hardware state machine, with side effects specified by the register definition.',
'Memory-mapped I/O uses ordinary address syntax to reach device behavior. A write-one-to-clear register clears the positions written as one; zero positions leave pending flags unchanged. Hardware may also change the register asynchronously. Startup, interrupt handlers, DMA, and RTOS tasks therefore interact through more than ordinary variable assignment.',
'A simulated W1C status register contains binary 1100. Software writes binary 0100, with no new hardware event during the operation.',
'Identify the written one-bit: bit two.|Clear that bit from the original status, leaving bit three unchanged.|The remaining status is binary 1000. The write did not replace the entire register with 0100.',
'A read–modify–write intended to preserve bits in RAM may clear multiple pending events in a W1C register. Read-to-clear fields have a different hazard: merely inspecting them can consume evidence. A volatile declaration does not establish the peripheral’s semantics or eliminate interleavings.',
'Read the register contract, access width, reserved-bit rules, and event timing. Use a precise mask for the intended operation and test event arrival around the access in a simulator. Keep interrupt latency and ownership explicit rather than hiding them behind a HAL call.',
'If software writes 1100 back to this W1C register, which original flags remain?',
'Neither original flag remains set|Both original flags remain set|Only the lowest bit of the register changes')

lesson(13,
'Firmware must keep working across resets, partial writes, and updates. Correct normal execution is only one part of its lifecycle.',
'Treat boot and update as state machines with authenticated inputs, protected policy state, atomic transitions, and recoverable failure paths.',
'An update signature checks whether the signed bytes were approved by a trusted signer. A version policy separately determines whether those approved bytes are still allowed. Compatibility and successful boot are further requirements. Staging an image, verifying it, switching slots, confirming health, and recovering after a reset are distinct transitions.',
'A toy device accepts an image only if its signature verifies and its authenticated version is at least 12. A signed version 11 arrives.',
'Check authenticity: the signature condition is true.|Check rollback policy: 11 >= 12 is false.|The conjunction fails, so reject the update without treating the valid signature as an override.',
'Power loss during an unprotected update can leave an incomplete image. A writable minimum-version counter can defeat rollback protection. Raising the minimum too early can also invalidate the only recoverable image.',
'Define failure behavior at every transition. Protect the trust anchor and rollback state, bind metadata to the signature, and test interruption at each write boundary in simulation. A/B slots help only when selection, confirmation, and recovery rules are sound.',
'Does a valid signature alone establish that an update is fresh enough?',
'No; version policy is a separate condition|Yes; all signed images are the latest release|Yes; signatures erase older vulnerabilities')

lesson(14,
'Firmware packages combine several formats and runtime roles. You need a method that distinguishes a format clue from a validated object and a file’s presence from its execution.',
'Preserve the image, map regions, propose a format, validate its structure, and trace how extracted components participate in boot or runtime.',
'Magic bytes are short signatures that suggest a parser to try. A parser can test lengths, offsets, version fields, and internal relationships. Entropy summarizes byte distribution, so compression and encryption can both appear highly variable. A validated filesystem provides files and paths; startup configuration then helps explain which programs are launched.',
'An offline image contains a candidate filesystem signature at offset 0x2000, but its stated directory table points beyond the end of the image.',
'Record the signature and offset as an initial hypothesis.|Check the declared boundaries against the available bytes.|Because the structure is inconsistent, label the region unconfirmed, truncated, or damaged rather than declaring successful extraction.',
'A magic-byte match may occur accidentally or inside compressed data. High entropy is not proof of encryption. Emulation may reach a shell while silently omitting a peripheral behavior relevant to the question.',
'Keep a pristine original and hashes, record extraction commands, and validate structural bounds. Distinguish package metadata, executable images, filesystems, and configuration. Explain emulation limitations explicitly and avoid claiming an observed file must execute.',
'What does a matching magic value with invalid internal offsets establish?',
'A format hypothesis requiring further validation|A fully valid filesystem|Proof that the region is encrypted')

lesson(15,
'IoT joins devices, gateways, messaging systems, and backend identities. Security reasoning must follow both telemetry and commands through this entire architecture.',
'Map who measures, who decides, who acts, and which identity may perform each operation on each resource.',
'A sensor observation is not an actuator command. A broker routes publications according to topics and subscriptions, while authentication establishes a credential holder and an ACL grants specific operations. TLS protects a connection under its validation policy, but does not derive topic ownership from a device name.',
'Device T3 may publish to T3/temperature and subscribe to T3/config. It requests permission to publish to T4/config over an authenticated TLS connection.',
'The TLS handshake establishes the connection’s authenticated identity.|The requested operation is publish and the target resource belongs to T4.|The ACL has no matching grant, so the publication is denied even though the connection remains authenticated.',
'An allow-all broker can turn one device credential into fleet-wide command authority. A gateway that forwards identities incorrectly can collapse trust boundaries. Provisioning errors may bind the right key to the wrong owner.',
'Write a flow map and operation/resource authorization matrix. Give telemetry and commands distinct privileges, validate onboarding, and plan credential rotation and retirement. Choose radio and transport technologies by constraints without assuming that connectivity provides authorization.',
'Which check decides whether T3 may publish to T4/config?',
'The broker’s operation-and-topic authorization policy|The radio signal strength|The presence of TLS alone')

lesson(16,
'Device security is a lifecycle problem. A secure-looking device can still retain backend authority after ownership changes or local data is erased.',
'Follow credentials and trust decisions across hardware, firmware, local services, apps, and the backend, including retirement and recovery.',
'A factory reset changes local state. A remote service maintains its own record of trusted credentials and device status. Unless that policy is updated, a previously copied credential can still authenticate. Hardware protection reduces extraction opportunities but does not tell a backend that a device has been retired.',
'A simulated retired sensor has its user settings erased. Its certificate serial remains active in a backend allowlist.',
'Separate the local reset event from the remote trust database.|A request carrying the still-valid credential satisfies the unchanged authentication policy.|Retirement requires a backend state change that makes the credential unacceptable, plus checks that the policy is enforced.',
'Shared factory secrets amplify one-device compromise into a fleet issue. LAN location is not identity. Deleting a label or renaming an account does not revoke a key.',
'Use unique identities, documented owner transitions, credential revocation, and verification of post-retirement rejection. Map default credentials, update paths, mobile APIs, and physical access to the same lifecycle model so controls cannot contradict one another.',
'Does deleting local settings automatically remove backend trust?',
'No; backend trust must be updated independently|Yes; the backend can infer every reset|Only if the device has a new display name')

lesson(17,
'RF concepts explain what a captured signal can tell you before protocol decoding begins. They prevent confusing reception quality with trustworthiness.',
'Trace physical signal → sampled waveform → symbols → packets → authenticated meaning, keeping each layer’s assumptions separate.',
'Modulation represents data through amplitude, frequency, phase, or combinations. Noise makes symbol decisions less reliable. SNR compares signal power with noise power; its decibel form is logarithmic, 10 log10 of a power ratio. Antennas, propagation, bandwidth, and interference affect observations before any packet parser runs.',
'A synthetic receiver measures signal power 50 units and noise power 5 units.',
'The power ratio is 50/5 = 10.|10 log10(10) gives an SNR of 10 dB.|If noise falls to 0.5 units with signal fixed, the ratio becomes 100 and SNR becomes 20 dB.',
'A strong signal can carry an unauthenticated or replayed packet. A decoded identifier is not proof of sender identity. Aliasing and poor sampling assumptions can create misleading waveform interpretations.',
'Record units, sample rate, channel settings, and noise assumptions. Validate framing and protocol integrity separately from cryptographic authenticity. Work with synthetic or recorded signals in this lab; no RF transmission is required.',
'What happens to SNR when noise rises while signal power stays fixed?',
'It decreases|It increases|It proves the sender is malicious')

lesson(18,
'Cryptography provides specific guarantees under explicit assumptions. Security failures often come from violating a protocol or key-use contract rather than breaking the underlying mathematics.',
'Name the desired property—confidentiality, integrity, authenticity, or freshness—and trace which primitive and key lifecycle rule provides it.',
'A stream cipher combines plaintext with a generated keystream using XOR. Reusing the same keystream makes it cancel when ciphertexts are XORed together. This exposes a relation between plaintexts without necessarily revealing the key. A public nonce can still require uniqueness: secrecy and uniqueness are different properties.',
'For toy four-bit strings, P1 = 1010, P2 = 0011, and the reused keystream is 1100.',
'C1 = 1010 XOR 1100 = 0110; C2 = 0011 XOR 1100 = 1111.|C1 XOR C2 = 1001.|P1 XOR P2 is also 1001 because the two copies of 1100 cancel. The ciphertext relation leaks plaintext structure.',
'A random-looking ciphertext does not establish safe nonce handling. A hash without a secret or signature does not authenticate an adversarial message. Encryption without an integrity mechanism does not establish that data was not modified.',
'Use vetted constructions according to their nonce, key, and message limits. Plan key generation, separation, storage, rotation, and revocation. Validate peer identity and certificate policy; do not invent a custom cipher to compensate for a broken application trust model.',
'Does the cancellation equation require the nonce to be secret?',
'No; avoiding repeated keystream is the relevant contract|Yes; a public nonce always exposes the key|No; therefore nonce reuse is harmless')

lesson(19,
'Malware analysis is evidence-based behavior reconstruction. It requires distinguishing capabilities, executed actions, and unsupported intent claims.',
'Connect inert process, file, persistence, and network observations into a timeline, then state the narrowest conclusion they support.',
'Static imports can suggest capabilities without proving they execute. Dynamic events show one run, possibly influenced by environment or prior state. A persistence mechanism arranges later execution, while exfiltration requires evidence of data leaving through some channel. A signature or IOC identifies a pattern, not an entire causal account.',
'An inert trace records a process writing an autostart configuration pointing to itself, then exiting. No network operation appears in this trace.',
'Identify the configuration’s startup role and the process that wrote it.|The write supports an attempted persistence mechanism.|The available record does not establish data exfiltration or rule out behavior on another path or run.',
'An empty trace can result from incomplete monitoring, unmet conditions, or environment detection. A benign administrative utility may use the same API as malware. A filename or isolated string does not establish intent.',
'Correlate artifacts, timestamps, and execution context; preserve alternative explanations. Analyze recorded data here. Do not execute live samples inside the web container: Docker’s deployment boundary is not a dedicated malware detonation environment.',
'What can this record directly support?',
'A persistence mechanism was configured|A kernel rootkit was installed|All possible exfiltration behavior is absent')

lesson(20,
'Windows analysis needs an object-and-rights model to interpret why a process can perform one operation and be denied another.',
'Distinguish process identity, token privileges, requested access, object policy, and the rights granted to a handle.',
'An access check evaluates a requested operation against a security context and object policy. Authentication or a familiar executable name is not a universal grant. Handles represent access to objects, while threads execute code in process context. Loader behavior, services, Registry state, and telemetry provide different pieces of the execution story.',
'A toy object policy permits READ and denies WRITE for a process token. The process requests a WRITE handle.',
'Identify the actual token rather than inferring it from the process name.|Compare the requested right WRITE with the object’s permitted rights.|Under this simplified policy the request is denied. Permission for READ would not authorize a write.',
'Assuming administrator-looking names imply every privilege leads to false conclusions. A loaded DLL is not evidence every exported function ran. A telemetry source observes a defined boundary and may omit other activity.',
'Record identity, requested rights, access result, and relevant object policy. Correlate ETW or other records with process and handle context. Treat the toy access rule as a learning abstraction; real access evaluation has additional policy details.',
'Can a READ-only grant justify a WRITE operation in this model?',
'No; the requested right must be authorized|Yes; any handle grants every right|Yes; the executable name decides permissions')

lesson(21,
'Linux research requires explaining how an executable’s runtime behavior depends on its loader, process state, privileges, and service configuration.',
'Trace a function or operation through symbol resolution and process context before attributing it to the kernel or to modified source code.',
'A dynamically linked program can resolve a function name through a preloaded shared library in applicable execution contexts. That changes the target implementation without editing source. Static binaries and secure-execution rules alter this behavior. /proc mappings can help identify what is loaded, while a trace can show what actually executes.',
'A toy non-privileged dynamically linked program calls a function named greet. A preloaded library defines greet and forwards to the usual implementation after recording the call.',
'The loader considers available symbol definitions under its resolution rules.|The application call reaches the interposed definition in this stated model.|The wrapper records the event and forwards it; this demonstrates user-space interposition, not by itself kernel modification.',
'Assuming every ELF uses a dynamic loader overgeneralizes from one binary. A suspicious library path does not prove a kernel rootkit. Namespaces and capabilities change context but do not independently prove complete containment.',
'Check binary linking, loader rules, mappings, and privilege context. Correlate service or startup configuration with runtime evidence. Preserve original files and avoid treating one environment-variable technique as a universal interception mechanism.',
'Would ordinary LD_PRELOAD interposition apply to a fully static version?',
'No; ordinary dynamic-loader interposition is absent|Yes; the environment rewrites machine instructions|Yes; ELF always means dynamically linked')

lesson(22,
'ICS diagrams only become useful when you can distinguish sensing, control, supervision, history, and safety functions. Otherwise a display failure can be mistaken for a process shutdown.',
'Trace separate measurement, decision, actuation, supervision, and protective paths, including their dependencies and failure modes.',
'A controller reads inputs and computes outputs. An HMI presents values and operator actions; a historian records selected data. A separately designed safety function may have independent sensors and final elements. Whether a failure propagates depends on actual dependencies, not the names of boxes in a diagram.',
'A synthetic ventilation system uses a controller to drive a fan and an HMI to show status. The display process stops while the controller and its inputs remain healthy.',
'Trace the normal control path: sensor → controller → fan.|The HMI is on the observation path, not in the stated control computation.|The controller can continue its defined logic even though the operator loses the display. Loss of visibility still matters operationally.',
'An HMI alarm is not automatically an independent trip. Shared power, networks, or sensors can defeat claimed redundancy. A healthy display does not establish that a valve physically moved.',
'Document which component measures, decides, acts, and verifies. For each failure, trace remaining dependencies and actuator behavior. Treat safety-function independence as a design property requiring evidence, not a label supplied by the diagram.',
'Does the specified display failure necessarily stop the controller?',
'No; its stated control path remains healthy|Yes; HMIs always execute the control loop|Yes; historians take over all outputs')

lesson(23,
'Control-system reasoning connects commands to physical consequences over time. It stops you treating a setpoint as an instantaneous measurement.',
'Track state, flows, feedback, units, and delay. Separate desired value, measured value, and actuator command.',
'A balance equation updates stored quantity from inflow minus outflow. Closed-loop control uses measured error to choose a command, but the process still obeys its dynamics. PID adds responses to current, accumulated, and changing error. Alarms, interlocks, and trips serve different roles and do not erase process inertia.',
'A synthetic tank starts with 20 L. Each step adds 4 L and removes 1 L. Rates remain constant for three steps.',
'The net change is +3 L per step.|Levels after successive steps are 23, 26, and 29 L.|Closing the inlet on the next step makes the change -1 L, giving 28 L rather than instantly emptying the tank.',
'Ignoring sample duration mixes flow rates with amounts. Reading only a setpoint hides sensor or actuator failures. “Stop everything” is not universally safe because the hazard depends on process dynamics and stored energy.',
'Write the state equation with units and explicit timing. Test disturbances and actuator limits in simulation. Explain what an interlock constrains and what an independent protective action must accomplish instead of relying on the appearance of an HMI symbol.',
'After the three specified steps, what level does the example predict?',
'29 L|12 L|20 L because the setpoint was unchanged')

lesson(24,
'PLC code interacts with sampled inputs and retained state. Understanding execution timing is necessary before interpreting a rung, timer, or online display.',
'Track physical input, sampled input image, logic state, and output update as distinct events under the stated runtime model.',
'In a simplified cyclic scan, sampling creates the input values used by logic; outputs are applied later. A physical edge after sampling does not retroactively alter that snapshot. Timers and function blocks retain state between invocations. Actual runtimes may include asynchronous I/O or additional tasks, so the simplified model must be named.',
'A toy scan samples Enable = TRUE. Physical Enable falls to FALSE immediately afterward. Logic assigns Lamp := Enable, then updates outputs.',
'The sampled input image contains TRUE.|Logic evaluates that stored image, assigning TRUE to the output image.|Lamp becomes TRUE at this update. If physical Enable remains FALSE, the next scan samples FALSE and turns Lamp off.',
'Confusing physical and sampled values predicts an immediate reaction that this model does not provide. A monitoring screen can miss brief transitions. Retentive state can also survive a restart when a learner expects initial values.',
'Draw a timeline with sample, logic, and update markers. Test edges on both sides of the sample and document retentive state. Use the actual runtime specification before applying this simplified conclusion to a physical PLC.',
'Which value does the current toy scan use after the physical falling edge?',
'The previously sampled TRUE value|The new physical FALSE value immediately|A random value because all sampling is unreliable')

lesson(25,
'Industrial protocol analysis starts by locating fields correctly and understanding the operation they request. A valid frame is not the same as an authorized or safe command.',
'Separate electrical transport, framing, field encoding, requested operation, authorization, and process consequence.',
'A Modbus TCP header identifies aspects of the transaction, while a function-specific PDU defines operation and arguments. Multi-byte fields must be interpreted under the documented byte order and offset rules. Register labels in manuals may differ from the on-wire starting address. Other industrial protocols use different object and session models.',
'An inert function-03 PDU is 03 00 20 00 04. The stated format is function, two-byte start address, and two-byte quantity, with big-endian fields.',
'Byte zero is function 03, read holding registers.|Bytes one and two form start address 0x0020.|Bytes three and four form quantity 0x0004, so four registers are requested. This field parsing does not establish permission.',
'Counting zero bytes or reading the transaction ID as quantity produces nonsense. A CRC can detect some corruption without authenticating a sender. A correctly encoded write may still violate process or access policy.',
'Build a byte-offset table, validate lengths, and consult the function definition. Keep address notation and multi-register word order explicit. Use inert frames here and validate the requested action against policy separately from syntax.',
'In this PDU, what quantity is requested?',
'Four registers|Thirty-two registers|Three registers because the function byte is 03')

lesson(26,
'An OT network diagram is a claim about communication boundaries. You need to translate that claim into enforceable and testable flows.',
'Model zones by security needs and conduits by specific permitted source, destination, service, direction, and purpose.',
'A DMZ can mediate selected exchanges so enterprise systems need not communicate directly with controllers. Segmentation works only when actual routes, firewalls, remote-access paths, and dependencies implement the policy. A private address or VLAN name has no inherent authorization meaning.',
'A synthetic policy permits an office reporting client to read a DMZ replica, while direct access to the controller zone is denied. A proposed rule allows the client to all controller ports.',
'Identify the required business flow: client → replica.|Compare it to the proposed destination and service range.|The proposed rule creates a different, broader conduit and contradicts the stated boundary.',
'An undocumented remote-access path can bypass the intended segmentation. Redundant links may preserve availability while accidentally preserving an unwanted route. “Air gap” claims fail when hidden connections or removable media bridge them.',
'Create an allowed-flow matrix, inspect effective routes and rules, and verify both permitted and denied synthetic flows. Begin discovery passively in sensitive contexts. Constrain remote access by identity and purpose as well as network reachability.',
'Which flow matches the stated requirement?',
'Office reporting client to the specified DMZ replica service|Office client to every controller port|Any flow between private IP addresses')

lesson(27,
'OT security decisions can change a physical process. The right response must account for operational state and consequences as well as evidence of compromise.',
'Connect suspected entry point → changed control state → possible physical effect → coordinated containment and verified recovery.',
'A logic checksum change shows a difference, not its cause or safe response. Engineering activity, faults, and malicious changes are competing explanations. Containment can remove harmful access, but abruptly stopping a controller may create another hazard. Recovery must restore a validated process state and dependencies, not only files.',
'A synthetic investigation finds an unfamiliar engineering session and a changed controller checksum. The process state is not yet known, but operations staff can help interpret it.',
'Preserve session and configuration evidence without assuming attribution.|Establish current controller, process, and protective-function state with the responsible operators.|Choose an approved containment action based on both the threat and the consequences of interrupting operation.',
'Treating every OT event like a disposable desktop incident can destroy evidence or worsen process risk. Restoring an old image without checking logic, I/O mappings, credentials, and restart conditions can recreate the failure.',
'Use inventory, baselines, scoped access, and a coordinated incident plan. Exercise response and recovery on a digital model. Record what evidence supports compromise and what remains uncertain; this lesson does not supply instructions for operating a real plant.',
'What is missing before selecting a disruptive response?',
'Knowledge of process state and coordinated operational consequences|A more dramatic incident name|Proof that the HMI uses a modern theme')

lesson(28,
'Frameworks help organize requirements, responsibility, and evidence. They become useful only when mapped to a concrete system and consequence.',
'Translate a high-level security objective into a specific control, a defined scope, an owner, and evidence that the control works.',
'Risk assessment relates threats and weaknesses to consequences under stated assumptions. Zones and conduits group protection needs and permitted flows. Defense in depth asks how controls interact and fail together. A framework label, maturity score, or checklist entry is not a measurement of an actual boundary.',
'A project claims that an industrial zone is segmented because its diagram contains a firewall icon. No effective rules or denied-flow test results are available.',
'Identify the security objective: only approved cross-zone traffic is allowed.|Specify the evidence needed: flow requirements, effective rules, ownership, and observed enforcement.|The icon documents intent; it does not yet demonstrate the control.',
'Confusing compliance paperwork with functioning protection leaves untested assumptions. Security levels and functional safety integrity levels address different concepts and should not be substituted for one another. A framework reference without a version or scope can also be ambiguous.',
'Use the applicable current framework or standard as a source of questions, then collect system-specific evidence. Keep scope, exceptions, risk ownership, and consequence assumptions explicit. This module teaches the mapping method, not certification or a reproduction of paid standards.',
'What best substantiates the segmentation claim?',
'Effective rules and evidence that required flows pass while prohibited flows are denied|A firewall icon alone|A statement that every framework requirement is complete')

lesson(29,
'Cyber-physical analysis must distinguish displayed data from actual process behavior and separate anomalies from proven malicious causes.',
'Compare independent observations and commands on an aligned timeline, then test competing explanations for disagreement.',
'A replayed or stale value can look plausible while the physical process changes. An independent measurement can falsify the claim that a display is current, but disagreement alone does not identify an attacker. Sensor faults, scaling, delays, and time alignment all influence interpretation.',
'A synthetic display holds 60 L while an independent gauge records 60, 63, and 66 L. The inlet command remains OPEN.',
'Align samples and identify which source supports the constant-level claim.|The independent increasing sequence contradicts a constant level under the stated model.|Check data age and the telemetry path before deciding whether the discrepancy is replay, stale data, or another fault.',
'A single plausible-looking HMI value can conceal change. Conversely, declaring every mismatch an attack overlooks benign failures. An actuator command is evidence of intent, not guaranteed physical movement.',
'Preserve independent traces, timestamps, and command context. Test alternative explanations using recorded or simulated data. Relate each proposed attack-chain step to observable evidence and a possible consequence without claiming attribution from one symptom.',
'If the display timestamp is old, what follows?',
'Stale telemetry is a plausible explanation to investigate|Sensor spoofing is conclusively proven|The independent gauge must be ignored')

lesson(30,
'Unknown protocols become understandable through controlled variation and prediction. A collection of decoded-looking bytes is not yet a specification.',
'Infer framing, fields, integrity checks, and session state, then challenge each hypothesis with a held-out observation.',
'Differential analysis changes one field while preserving other conditions. Constant bytes may identify framing; varying bytes may encode values, lengths, or checksums. A checksum equation should predict unseen frames. Stateful messages additionally depend on sequence and prior exchanges, so field decoding alone may not explain acceptance.',
'A toy payload consists of bytes 05 and 03. Its checksum is explicitly defined as XOR of payload bytes only.',
'Compute binary 0101 XOR 0011 = 0110, giving checksum 06.|Change only the second payload byte to 02.|Predict checksum 07 and compare it with a held-out frame. A correct prediction supports this rule within the toy model.',
'Two matching examples can fit several checksum hypotheses. A CRC or XOR check does not authenticate intent because an adversary may recompute it. A parser rejection can also be caused by session state rather than malformed field syntax.',
'Keep original captures and a field map with confidence levels. Separate length, checksum, and semantic hypotheses; design one-variable tests and validate on new traces. Fuzz only the isolated synthetic parser or another explicitly authorized environment.',
'Can someone modify the payload and recompute this XOR checksum?',
'Yes; this checksum is not cryptographic authentication|No; XOR proves sender identity|Only if the frame is encrypted')

lesson(31,
'Boot is where a system first decides what code to trust. Understanding that decision prevents confusing a recorded hash with an enforced execution policy.',
'Trace the root of trust and each handoff; distinguish measuring code, verifying authorization, blocking execution, and later reporting evidence.',
'Measured boot records properties of loaded components for later appraisal. Secure-boot enforcement checks a policy before allowing a stage to execute. Attestation adds an identity and freshness context to reported evidence. A trusted measurement register does not, by itself, force a loader to refuse an unapproved image.',
'A toy ROM hashes an image into protected state and always jumps to it. A later service can report that hash.',
'The measurement establishes an observable identity of the bytes under the stated hash assumptions.|The control-flow path has no refusal decision.|An unapproved image can still execute; a verifier may later detect that its measurement is not allowed.',
'A verified early stage can hand off to an unchecked later stage. A valid old signature may bypass freshness expectations without rollback policy. A measurement report without freshness can be replayed.',
'Draw each verification and execution edge, identify immutable assumptions, and test rejection behavior using synthetic images. Specify signing, revocation, rollback, recovery, and attestation appraisal policies separately.',
'What must be added to prevent execution of unapproved images in this toy design?',
'An enforced authorization decision before execution|A second copy of the same recorded hash|A more descriptive image filename')

lesson(32,
'Hardware security requires matching a control to the access path it actually protects. Locking one interface does not protect every copy of an asset.',
'Locate the secret or decision, enumerate independent interfaces and storage paths, and state what each control prevents under the threat model.',
'A debug lock restricts a debug interface. Storage encryption protects confidentiality of stored bytes under its key assumptions; authentication protects integrity and origin. A secure element may constrain key extraction while still offering operations to an authorized caller. These controls have different boundaries and lifecycle dependencies.',
'A toy design locks CPU debugging but stores a service credential in plaintext external storage. An authorized researcher receives an offline copy of that storage.',
'Identify the asset: the credential’s bytes.|Identify the provided access path: an independent storage copy, not the locked debug interface.|The debug restriction does not change the plaintext representation in that copy.',
'Physical access assumptions may omit exposed buses, recovery modes, or provisioning paths. Integrity protection alone does not hide a secret. A protected key can still be misused through an overly permissive operation interface.',
'Map debug, storage, boot, and provisioning boundaries separately. Minimize stored secrets, define allowed key operations, and test lifecycle transitions in a documented model. This exercise analyzes a supplied copy and does not require invasive extraction.',
'Does authenticating the external storage alone conceal its plaintext?',
'No; integrity and confidentiality are different properties|Yes; every signature encrypts its input|Only if the debug port is locked')

lesson(33,
'Emulation makes systems observable and repeatable only within its model. Understanding its boundary prevents overclaiming what a simulation has established.',
'List every state component and external dependency that can affect the result, then ask what a snapshot actually restores.',
'CPU emulation models instruction behavior; system emulation adds selected devices; virtualization uses hardware support for guest execution. A snapshot may include CPU and RAM but omit an external service, physical time, or device backend. Replaying the same disk image can therefore produce different inputs.',
'A toy snapshot restores a guest but not its external simulated clock service. Before restore the service returns tick 100; afterward it returns tick 101.',
'The guest state was restored according to the snapshot contract.|The external clock retained its independently advancing state.|A different observation is expected unless the external input is also recorded and replayed or reset.',
'Assuming a snapshot resets the world hides dependencies. A successful firmware run with peripheral stubs may not reproduce timing or error behavior. A digital twin can model control logic accurately while simplifying the physical process.',
'Document included and excluded state, use deterministic recorded inputs when appropriate, and compare traces after reset. Explain which conclusion depends on model fidelity and which holds just within the simulator.',
'What should you inspect first when restored runs receive different ticks?',
'The external service’s omitted state|The browser font settings|Proof that every CPU instruction is broken')

lesson(34,
'Program analysis formalizes how values and paths produce behavior. It helps locate missing conditions instead of treating the existence of a check as proof of safety.',
'Trace influence from inputs to operations and combine every path predicate with the operation’s full preconditions.',
'A control-flow graph describes possible transfers; data flow tracks definitions and uses. Taint tracks influence under chosen rules, not maliciousness itself. A symbolic path condition states which inputs reach an operation. Proving an array access safe requires both lower and upper bounds, plus a valid object and suitable arithmetic semantics.',
'In mathematical pseudocode, y = x + 2; if y < 5 then write array[y]. Valid indices are 0 through 4. Consider x = -3.',
'Substitute x: y becomes -1.|The upper-bound condition -1 < 5 is true.|The write reaches an invalid negative index because the lower-bound requirement was never established.',
'A comparison can look like sanitization while proving the wrong predicate. Static approximations can report infeasible paths; dynamic coverage can miss unexecuted ones. Machine integer overflow can invalidate reasoning performed over unbounded mathematical integers.',
'Write the full access precondition, examine both branches, and test boundary values. State whether the analysis uses machine-width or mathematical arithmetic. Combine static hypotheses with controlled observations without treating one tool’s silence as proof.',
'Which additional predicate excludes the demonstrated negative-index path?',
'y >= 0|y != 100|x has a short variable name')

lesson(35,
'Automated input generation is useful only when failures are observable, repeatable, and explainable. Fuzzing turns into research through harness design and triage.',
'Treat the fuzzer as an experiment loop: initialize state, generate input, observe behavior, retain useful evidence, reset, and reproduce.',
'A harness exposes a target under controlled setup. Coverage feedback helps select inputs that explore different execution, but it does not establish semantic correctness. Minimization removes input portions while preserving a specified failure, making the relevant condition easier to understand. Deduplication groups symptoms provisionally rather than proving identical root causes.',
'A toy parser fails exactly when adjacent bytes DE AD appear. The recorded input is 01 DE AD 02.',
'Replay the original input after a clean reset.|Remove 01 and 02 while checking that the same failure still occurs.|Test single-byte removals from DE AD; neither triggers the stated condition, so the pair is minimal for this toy failure.',
'Without resetting state, an input may appear causal only because a previous test primed the parser. A crash can be nondeterministic or unrelated to the intended failure. The shortest input is not necessarily the most interesting coverage sample.',
'Preserve seed, build, configuration, and failure signature. Minimize against the same failure criterion, then perform root-cause analysis. Use inert local targets in this lab and distinguish corpus exploration from claiming a vulnerability’s impact.',
'What must remain true during crash minimization?',
'The same relevant failure is still reproducible|Every original byte is retained|The input becomes valid under every grammar')

lesson(36,
'Python makes binary transformations inspectable, but convenient language behavior can conceal machine-width and transport assumptions.',
'Treat bytes as an explicit format with offsets, widths, byte order, bounds, and expected state; do not let host defaults define the protocol.',
'struct unpacking maps bytes to values under a format. Little-endian assigns the first byte the lowest weight; big-endian assigns it the highest. Python integers are not ordinary fixed-width wrapping machine integers, so model narrowing deliberately. Sockets may deliver partial data, which must be assembled before decoding a complete field.',
'blob = bytes.fromhex("02 01"). Decode one unsigned 16-bit value with format <H.',
'The < explicitly selects little-endian and H selects an unsigned two-byte field in this format.|Compute 0x02 + (0x01 × 256) = 258.|Changing to >H instead gives 0x0201 = 513; the bytes did not change, only the interpretation did.',
'Unpacking before checking length raises errors or hides a larger framing bug. Decoding arbitrary binary data as text can destroy the intended interpretation. An unbounded length can also drive excessive allocation even in a memory-managed language.',
'Validate available bytes and declared limits, choose explicit format prefixes, and test truncated and oversized input. Preserve raw bytes alongside decoded results. Submitted scripts remain inert evidence rather than running in the web service.',
'Which assumption controls the byte order in this example?',
'The explicit struct format prefix|The file extension|The variable name blob')

lesson(37,
'Research results need reproducible software and clear contracts. Otherwise a changed dependency can be mistaken for a newly discovered behavior.',
'Model an artifact as the result of source, toolchain, dependencies, configuration, and environment—not source revision alone.',
'A build transforms inputs through tools with specific versions and flags. Locks constrain dependency choices; tests exercise defined contracts; logs explain observed execution. A reproducible build aims for identical artifacts given the same complete inputs, while functional tests ask whether behavior satisfies chosen properties. Those are related but distinct checks.',
'Two toy builds use the same source commit. One uses compiler version A with optimization disabled; the other uses version B with optimization enabled.',
'The source input is identical.|The transformation tools and options differ, so generated instructions or metadata may differ.|Different binary hashes are unsurprising and do not alone establish malicious modification or changed functional behavior.',
'Hidden timestamps, paths, floating dependencies, or environment variables undermine reproducibility. A passing unit test suite may miss an integration boundary. Logging secrets can create a security problem while attempting to improve diagnosis.',
'Record tool versions, lock dependencies, define tests around behavior and boundaries, and preserve minimal reproducers. Review changes against invariants and expected failure behavior. Treat profiling as evidence about cost rather than guessing from code appearance.',
'Does the source commit alone determine the binary hash?',
'No; other build inputs can affect the artifact|Yes; compiler versions are irrelevant|Only if the filename ends in exe')

lesson(38,
'Security engineering connects an asset and policy to a concrete enforcement point. It prevents broad slogans like “users are authenticated” from replacing resource-level checks.',
'At each trust boundary, identify the actor, requested action, target resource, policy decision, and enforcement result.',
'Authentication identifies a credential holder. Authorization decides whether that holder may perform an operation on this object. A user interface can hide a button while the server still accepts the underlying request. Least privilege limits the operations that remain possible after a component or credential is compromised.',
'User R is logged in and owns document R1. The service receives a request for another user’s document S1 and checks only whether the session is valid.',
'The session check establishes a logged-in identity.|The requested object is S1, so ownership or another policy grant must be checked for that object.|Without that decision, the request can cross an unintended trust boundary even though authentication succeeded.',
'Random identifiers make guessing harder but do not enforce ownership. A global role check may miss object-specific constraints. An SBOM identifies components but does not prove their safe configuration or reachability.',
'Enforce policy server-side for each operation and resource, test both allowed and denied cases with distinct identities, and minimize credential authority. Map secret storage, update trust, provisioning, and revocation to the same enforcement model.',
'Would replacing document IDs with random UUIDs repair the missing ownership check?',
'No; authorization must still be enforced|Yes; unpredictable names grant ownership|Yes; authentication becomes unnecessary')

lesson(39,
'Vulnerability research turns anomalies into reproducible, bounded claims. The methodology matters as much as the tool that first reports a problem.',
'Move from scoped entry point through reachable data flow to the earliest broken invariant, then test a fix and state supported impact.',
'A patch changes a program predicate or transition. Understanding the change requires connecting it to the operation’s actual precondition. A boundary comparison may be wrong by one when the operation includes a terminator or extra byte. Reproduction establishes a concrete path; exploitability needs additional evidence about control and consequences.',
'A toy six-byte destination receives n + 1 bytes after a guard n <= 6. n is nonnegative and arithmetic does not overflow in this model.',
'The destination permits at most six bytes.|At n = 6, the guard passes but the write length is seven.|The proper bound for this stated contract is n < 6. Test n = 5 and n = 6 to distinguish valid and invalid boundaries.',
'A changed comparison is not proof every caller and arithmetic assumption is safe. A crash does not automatically establish code execution. Omitting the exact build or input prevents others from reproducing the evidence.',
'Record scope, version, input, expected and observed behavior, earliest invalid operation, and limitations. Check arithmetic and object contracts around the patch. Coordinate disclosure through the authorized owner and keep demonstrated impact separate from conjecture.',
'Which n exposes this example’s original off-by-one write?',
'6|0|5')

lesson(40,
'Mathematics gives precise language for uncertainty, finite representations, and relationships between observations. It helps identify when an intuitive claim exceeds its assumptions.',
'Write the sample space, distribution, algebraic structure, and independence assumptions before calculating a result.',
'A uniform n-bit draw has 2^n equally likely outcomes, so one fixed valid guess succeeds with probability 1/2^n. Storage width alone does not establish that distribution. Modular arithmetic describes residues under a chosen modulus, while finite fields have their own operation rules. Graphs and Boolean predicates model paths and state constraints.',
'A toy random source chooses uniformly from sixteen values, 0 through 15. A guess is fixed before one independent draw.',
'Count the possible outcomes: sixteen.|Exactly one outcome matches the fixed valid guess.|The probability is 1/16. If the source instead chooses only four equally likely values, a valid fixed guess succeeds with probability 1/4.',
'Inspecting one random-looking output cannot establish uniformity or unpredictability. Correlated draws invalidate naive independence calculations. Entropy measures a distribution rather than the visual complexity of one file.',
'State assumptions and units, distinguish observations from the generating process, and test sensitivity to changed distributions. Use appropriate sample-based methods to evaluate evidence without treating a finite sample as a universal proof.',
'If only four equally likely outcomes are possible, what is one valid fixed guess’s success probability?',
'1/4|1/16|Zero because the value is random')

lesson(41,
'Research skills make learning cumulative: another person should be able to follow your evidence, reproduce your experiment, and identify what would change your mind.',
'Separate observation, interpretation, hypothesis, intervention, and conclusion, preserving both supporting and disconfirming results.',
'A causal hypothesis predicts what should change when one relevant variable changes while others remain controlled. If two factors change together, either may explain the outcome. Repeating a result tests stability, while a held-out condition probes the hypothesis’s limits. Sources also have scope: a normative statement, an example, and a particular implementation trace are different kinds of evidence.',
'You hypothesize that flag F causes a toy parser to reject a message. Trial A changes F and the message length; trial B changes only F while preserving a valid length.',
'Compare each trial to the same accepted baseline.|Trial A has two competing explanations for rejection.|Trial B better isolates the effect of F, though additional conditions or hidden state may still matter.',
'Collecting only confirming trials creates a misleading record. A screenshot without bytes, versions, or steps may not be reproducible. Treating a source comment as a guaranteed runtime fact skips verification.',
'Keep a timestamped record of question, setup, exact input, prediction, observation, explanation, and limitations. Cite source versions and sections. When a controlled counterexample appears, revise the model and design the next discriminating experiment.',
'Which trial better isolates the proposed effect of F?',
'Trial B, because length is controlled|Trial A, because more variables change|Neither, because hypotheses cannot be tested')
